// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_SubWorkPlan
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewSubWorkPlan
    {
        public long SubWpId { get; set; } // SubWP_ID
        public long WpId { get; set; } // WP_ID
        public int SupervisorId { get; set; } // Supervisor_ID
        public string Name { get; set; } // Name
        public string SubWpQty { get; set; } // SubWP_Qty (length: 10)
        public System.DateTime SubWpEntryDate { get; set; } // SubWP_EntryDate
        public int UserId { get; set; } // UserID
        public string SessionYear { get; set; } // Session_Year (length: 20)

        public ViewSubWorkPlan()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
