// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_ShowCapitalGoods
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewShowCapitalGood
    {
        public long? Qty { get; set; } // Qty
        public string Purpose { get; set; } // Purpose
        public long? RItemId { get; set; } // RItem_Id
        public string CapName { get; set; } // CapName (length: 50)
        public string Unit { get; set; } // Unit (length: 50)
        public string OutPassNo { get; set; } // OutPass_No (length: 50)
        public System.DateTime? OutPassDate { get; set; } // OutPass_Date
        public string Comments { get; set; } // Comments
        public string OutPassBy { get; set; } // OutPass_By (length: 50)
        public long? OutPassId { get; set; } // OutPass_ID
        public string CapCode { get; set; } // CapCode (length: 50)
        public string SubCategory { get; set; } // SubCategory (length: 50)
        public long TableId { get; set; } // Table_ID
        public int CapId { get; set; } // CapID

        public ViewShowCapitalGood()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
