// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Ins_Item
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewInsItem
    {
        public long InsId { get; set; } // Ins_ID
        public long ItemId { get; set; } // Item_ID
        public int Qty { get; set; } // Qty
        public int TotalQty { get; set; } // Total_Qty
        public string ItemCode { get; set; } // ItemCode (length: 50)

        public ViewInsItem()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
