// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_SIP
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewSip
    {
        public string SipNo { get; set; } // SIP_No (length: 50)
        public string GipNo { get; set; } // GIPNo (length: 50)
        public System.DateTime SipDate { get; set; } // SIP_Date
        public string SipBy { get; set; } // SIP_By (length: 50)
        public string SessionYear { get; set; } // SessionYear (length: 50)
        public int UserId { get; set; } // User_Id
        public string PName { get; set; } // P_Name
        public long SipId { get; set; } // SIP_Id
        public int? PoFor { get; set; } // PO_for

        public ViewSip()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
