// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_CancelOrderList
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewCancelOrderList
    {
        public long OrderCancelId { get; set; } // Order_Cancel_ID
        public long OrderId { get; set; } // Order_ID
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public System.DateTime CancelDate { get; set; } // Cancel_Date
        public string CancelReason { get; set; } // Cancel_Reason
        public int UserId { get; set; } // User_ID
        public string SessionYear { get; set; } // Session_Year (length: 50)
        public System.DateTime EntryDate { get; set; } // Entry_Date

        public ViewCancelOrderList()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
