// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_TeatmentChart
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewTeatmentChart
    {
        public int TreatmentId { get; set; } // TreatmentID
        public string Treatment { get; set; } // Treatment (length: 50)
        public string TreatmentDesc { get; set; } // TreatmentDesc (length: 100)
        public System.DateTime? EntryDate { get; set; } // Entry_Date
        public string Refrence { get; set; } // Refrence (length: 50)
        public int? WaxFlSkHard { get; set; } // Wax_Fl_sk_Hard
        public int? WaxFlSkLight { get; set; } // Wax_Fl_sk_Light
        public int? WaxCompLight { get; set; } // Wax_Comp_Light
        public int? WaxCompMedium { get; set; } // Wax_Comp_Medium
        public int? WaxCompHard { get; set; } // Wax_Comp_Hard
        public int? WaxComplBgLight { get; set; } // Wax_Compl_bg_Light
        public int? WaxComplBgHard { get; set; } // Wax_Compl_bg_Hard
        public int? TumblingSkin { get; set; } // Tumbling_skin
        public int? TumblingBag { get; set; } // Tumbling_bag
        public int? WashingSkin { get; set; } // Washing_skin
        public int? Making { get; set; } // Making
        public int? WashingBag { get; set; } // Washing_bag
        public string Comments { get; set; } // comments (length: 150)

        public ViewTeatmentChart()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
