// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_ITCHS_Code
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewItchsCode
    {
        public int? ItcId { get; set; } // ItcID
        public string ItcCode { get; set; } // ItcCode (length: 50)
        public string ItemName { get; set; } // ItemName (length: 50)
        public int? InvoiceSerial { get; set; } // InvoiceSerial
        public string Category { get; set; } // Category (length: 50)
        public string CName { get; set; } // CName (length: 50)
        public string AddressOffice { get; set; } // Address_office

        public ViewItchsCode()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
