// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_CareLavels
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewCareLavel
    {
        public int Cid { get; set; } // CID
        public string Clname { get; set; } // CLNAME (length: 50)
        public string Description { get; set; } // Description (length: 100)
        public System.DateTime? EntryDate { get; set; } // Entry_Date
        public int? BuyerId { get; set; } // Buyer_Id
        public string PName { get; set; } // P_Name
        public string Address { get; set; } // Address
        public string City { get; set; } // City
        public string State { get; set; } // State

        public ViewCareLavel()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
