// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_PurchaseVoucher_With_Tax
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewPurchaseVoucherWithTax
    {
        public string AccName { get; set; } // AccName (length: 100)
        public long PVoucherId { get; set; } // P_Voucher_Id
        public long Sid { get; set; } // SID
        public int AccNo { get; set; } // AccNo
        public System.DateTime PVoucherDate { get; set; } // P_Voucher_Date
        public double TotalAmount { get; set; } // TotalAmount
        public double? TaxTotal { get; set; } // Tax_Total
        public double? Total { get; set; } // Total
        public double? Roundoff { get; set; } // Roundoff
        public double? VoucherAmt { get; set; } // Voucher_Amt
        public string Remark { get; set; } // Remark
        public string AmtInWords { get; set; } // AmtInWords
        public int? SipOrDirect { get; set; } // SIP_or_Direct
        public string Billno { get; set; } // Billno (length: 50)
        public System.DateTime? BillDate { get; set; } // BillDate
        public long? PVoucherSId { get; set; } // P_Voucher_SId
        public string RmName { get; set; } // RMName (length: 500)
        public double Quantity { get; set; } // Quantity
        public string Unit { get; set; } // Unit (length: 50)
        public decimal Rate { get; set; } // Rate
        public long RmId { get; set; } // RM_Id
        public long? GrnId { get; set; } // GRN_Id
        public decimal? Amount { get; set; } // Amount
        public string PName { get; set; } // P_Name
        public string Address { get; set; } // Address
        public string City { get; set; } // City
        public string State { get; set; } // State
        public string PartAccount { get; set; } // PartAccount (length: 100)
        public string CName { get; set; } // CName (length: 50)
        public string AddressOffice { get; set; } // Address_office
        public string AddressWork { get; set; } // Address_work
        public string Phone { get; set; } // Phone (length: 50)
        public string Fax { get; set; } // Fax (length: 50)
        public string Email { get; set; } // Email (length: 100)
        public string Web { get; set; } // Web (length: 100)
        public string Cstt { get; set; } // CSTT (length: 50)
        public string Uptt { get; set; } // UPTT (length: 50)
        public string Tin { get; set; } // TIN (length: 50)
        public string Pincode { get; set; } // Pincode (length: 20)
        public string Zipcode { get; set; } // Zipcode (length: 20)
        public string Phoneno { get; set; } // Phoneno (length: 20)
        public string Country { get; set; } // Country

        public ViewPurchaseVoucherWithTax()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
