// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // The table 'View_User_Permission' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // View_User_Permission
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewUserPermission
    {
        public int? SNo { get; set; } // SNo
        public int? UserId { get; set; } // UserID
        public string Save { get; set; } // Save (length: 1)
        public string Modify { get; set; } // Modify (length: 1)
        public string Delete { get; set; } // Delete (length: 1)
        public int? MenuId { get; set; } // MenuID
        public int? BelongTo { get; set; } // Belong_to
        public string Menu { get; set; } // Menu (length: 100)

        public ViewUserPermission()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
