// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_FillWorkplanDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewFillWorkplanDetail
    {
        public string Code { get; set; } // Code (length: 500)
        public string ItemCode { get; set; } // ItemCode (length: 500)
        public System.DateTime PlanDate { get; set; } // Plan_Date
        public string PlanBy { get; set; } // Plan_By (length: 50)
        public string Size { get; set; } // Size (length: 50)
        public string Color { get; set; } // Color (length: 50)
        public long PlanId { get; set; } // Plan_Id
        public long OrderId { get; set; } // Order_Id
        public int PlanFor { get; set; } // Plan_For
        public int SupervisorId { get; set; } // Supervisor_Id
        public int PlanQty { get; set; } // Plan_Qty
        public long ItemId { get; set; } // Item_Id
        public string SessionYear { get; set; } // Session_Year (length: 20)
        public int UserId { get; set; } // UserID
        public string Comments { get; set; } // Comments
        public string ConSupName { get; set; } // Con_Sup_Name
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public string OrderNo { get; set; } // Order_No (length: 50)

        public ViewFillWorkplanDetail()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
