// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_pck
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewPck
    {
        public long InsId { get; set; } // Ins_ID
        public long OrderId { get; set; } // Order_ID
        public long ItemId { get; set; } // Item_ID
        public int ItemQtyInAss { get; set; } // item_qty_in_ass
        public int AssInInner { get; set; } // Ass_in_inner
        public string ItemCode { get; set; } // ItemCode (length: 500)
        public string Quality { get; set; } // Quality (length: 50)
        public string Color { get; set; } // Color (length: 50)
        public string ItemSize { get; set; } // Item_Size (length: 50)
        public long PckId { get; set; } // PCK_Id
        public string PckNo { get; set; } // PCK_No (length: 50)
        public System.DateTime PckDate { get; set; } // PCK_Date
        public string Diemension { get; set; } // Diemension (length: 50)
        public int NoofOuter { get; set; } // Noof_Outer
        public int Pcs { get; set; } // Pcs
        public int InnerInCarton { get; set; } // inner_in_carton
        public int PackAssNo { get; set; } // Pack_Ass_No
        public int? QtyInCarton { get; set; } // qty_in_carton
        public int? QtyInPack { get; set; } // qty_in_pack
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public string CName { get; set; } // CName (length: 50)
        public string AddressOffice { get; set; } // Address_office
        public string AddressWork { get; set; } // Address_work
        public string Phone { get; set; } // Phone (length: 50)
        public string Fax { get; set; } // Fax (length: 50)
        public string Email { get; set; } // Email (length: 100)
        public string Web { get; set; } // Web (length: 100)
        public string Cstt { get; set; } // CSTT (length: 50)
        public string Uptt { get; set; } // UPTT (length: 50)
        public string Tin { get; set; } // TIN (length: 50)
        public string IeCode { get; set; } // IECode (length: 50)
        public string EmpEsiCode1 { get; set; } // EmpEsiCode1
        public string EmpEsiCode2 { get; set; } // EmpEsiCode2
        public string EmpEsiCode3 { get; set; } // EmpEsiCode3
        public string EmpPfEsttCode { get; set; } // EmpPfEsttCode
        public decimal? Excise { get; set; } // Excise
        public string CustomTeriffNo { get; set; } // CustomTeriffNo (length: 50)
        public string PanNo { get; set; } // PANNo (length: 50)
        public int BelongTo { get; set; } // BelongTo
        public string ParantItemCode { get; set; } // Parant_item_code (length: 500)
        public long ParantItemId { get; set; } // Parant_item_id
        public string ItcCode { get; set; } // ItcCode (length: 50)
        public int? InvoiceSerial { get; set; } // InvoiceSerial
        public string ItemName { get; set; } // ItemName (length: 50)
        public decimal Rate { get; set; } // Rate
        public string ColorDesc { get; set; } // Color_Desc (length: 100)
        public string QliDesc { get; set; } // QliDesc (length: 100)
        public int Tid { get; set; } // TID
        public string TranportName { get; set; } // TranportName (length: 50)
        public string FobCif { get; set; } // FOB_CIF (length: 50)

        public ViewPck()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
