// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Way_Packing
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewWayPacking
    {
        public long? Id { get; set; } // ID
        public long? ItemId { get; set; } // Item_ID
        public string OrderNo { get; set; } // Order_No (length: 50)
        public string ItemCode { get; set; } // Item_Code (length: 50)
        public string Quality { get; set; } // Quality (length: 50)
        public string Color { get; set; } // Color (length: 50)
        public string Size { get; set; } // Size (length: 50)
        public int? PcsPerCartoon { get; set; } // Pcs_per_Cartoon
        public int? TotalPcs { get; set; } // Total_Pcs
        public string Carton { get; set; } // Carton (length: 50)
        public string Remark { get; set; } // Remark (length: 50)
        public int? SNo { get; set; } // S_No
        public string ItemName1 { get; set; } // Item_Name (length: 50)
        public long? InsId { get; set; } // Ins_Id
        public int? NoOfCarton { get; set; } // No_of_Carton
        public long? ParantItemId { get; set; } // Parant_item_id
        public string ItcCode { get; set; } // ItcCode (length: 50)
        public string ItemName { get; set; } // ItemName (length: 50)
        public int? InvoiceSerial { get; set; } // InvoiceSerial
        public decimal Rate { get; set; } // Rate
        public long WayId { get; set; } // Way_ID
        public string PackingNo { get; set; } // Packing_No (length: 50)
        public System.DateTime? WayDate { get; set; } // Way_Date
        public int? TotalCarton { get; set; } // Total_Carton
        public decimal? GrossWt { get; set; } // Gross_wt
        public decimal? NetWt { get; set; } // Net_wt
        public int? WayNoAgainstPacking { get; set; } // Way_No_Against_Packing
        public int OrderId { get; set; } // Order_Id

        public ViewWayPacking()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
