// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Sales_Voucher
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewSalesVoucher
    {
        public string PName { get; set; } // P_Name
        public int AccNo { get; set; } // AccNo
        public string AccName { get; set; } // AccName (length: 100)
        public int SuppBuyerEmpId { get; set; } // Supp_Buyer_EMP_ID
        public int SuppBuyerEmp { get; set; } // Supp_Buyer_EMP
        public string CsName { get; set; } // CSName (length: 50)
        public string ItemCode { get; set; } // ItemCode (length: 50)
        public string Description { get; set; } // Description
        public long Qty { get; set; } // Qty
        public double Amount { get; set; } // Amount
        public long SNo { get; set; } // SNo
        public long InvoiceId { get; set; } // InvoiceID
        public string Packingno { get; set; } // Packingno (length: 50)
        public long Sid { get; set; } // SID
        public long? ConsigneeId { get; set; } // Consignee_Id
        public string ConsigneeAdd { get; set; } // Consignee_Add
        public string Notify { get; set; } // Notify
        public string PreCarrigeby { get; set; } // Pre_carrigeby (length: 50)
        public string PlaceOfReceipt { get; set; } // Place_of_Receipt (length: 50)
        public string VesselFlightNo { get; set; } // Vessel_Flight_No (length: 50)
        public string PortOfLoading { get; set; } // Port_of_Loading (length: 50)
        public string PortOfDischarge { get; set; } // Port_of_Discharge (length: 50)
        public string PortOfDelivery { get; set; } // Port_of_Delivery (length: 50)
        public string InvoiceNo1 { get; set; } // InvoiceNo (length: 50)
        public System.DateTime InvoiceDate { get; set; } // InvoiceDate
        public string BuyerOrderno { get; set; } // Buyer_Orderno (length: 50)
        public string OtherRefrence { get; set; } // Other_Refrence (length: 50)
        public string BuyerIfOther { get; set; } // Buyer_if_Other (length: 50)
        public string CountryOfOrigin { get; set; } // Country_of_Origin (length: 50)
        public string CountryOfDestination { get; set; } // Country_of_Destination (length: 50)
        public string Terms { get; set; } // Terms
        public long? Cid { get; set; } // CID
        public string InvoiceType { get; set; } // Invoice_Type (length: 50)
        public long? InvoiceNo { get; set; } // Invoice_No
        public string AddressWork { get; set; } // Address_work
        public string AddressOffice { get; set; } // Address_office
        public string Cstt { get; set; } // CSTT (length: 50)
        public string Uptt { get; set; } // UPTT (length: 50)
        public string Tin { get; set; } // TIN (length: 50)
        public string ExporterRefrence { get; set; } // ExporterRefrence (length: 50)
        public string AmtWords { get; set; } // AmtWords
        public string SessionYear { get; set; } // Session_year (length: 20)
        public int? UserId { get; set; } // UserID
        public decimal? InvoiceAmount { get; set; } // Invoice_Amount
        public string Fax { get; set; } // Fax (length: 50)
        public string Phone { get; set; } // Phone (length: 50)
        public string Name { get; set; } // Name (length: 50)
        public string Unit { get; set; } // Unit (length: 50)
        public string ItcHs { get; set; } // ITC_HS (length: 50)
        public string Size { get; set; } // Size (length: 50)
        public string Colour { get; set; } // Colour (length: 50)
        public double Rate { get; set; } // Rate
        public string CName { get; set; } // CName (length: 50)
        public long FItemId { get; set; } // FItem_Id
        public string ItcCode { get; set; } // ItcCode (length: 50)
        public string ItemName { get; set; } // ItemName (length: 50)
        public int? InvoiceSerial { get; set; } // InvoiceSerial
        public string ConsigneeName { get; set; } // Consignee_name (length: 50)
        public string PayemntTerm { get; set; } // Payemnt_Term
        public string BlAwb { get; set; } // BL_AWB (length: 100)
        public string PackingRemark { get; set; } // Packing_Remark
        public string TotalCarton { get; set; } // Total_Carton (length: 50)
        public string OrderNo { get; set; } // OrderNo (length: 50)
        public string Quality { get; set; } // Quality (length: 50)
        public string FobCif { get; set; } // FOB_CIF (length: 50)

        public ViewSalesVoucher()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
