// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Way_PackingPrint
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewWayPackingPrint
    {
        public long WayId { get; set; } // Way_ID
        public string PackingNo { get; set; } // Packing_No (length: 50)
        public System.DateTime? WayDate { get; set; } // Way_Date
        public int? TotalCarton { get; set; } // Total_Carton
        public decimal? GrossWt { get; set; } // Gross_wt
        public decimal? NetWt { get; set; } // Net_wt
        public int? WayNoAgainstPacking { get; set; } // Way_No_Against_Packing
        public long? ItemId { get; set; } // Item_ID
        public string OrderNo { get; set; } // Order_No (length: 50)
        public string ItemCode { get; set; } // Item_Code (length: 50)
        public string Quality { get; set; } // Quality (length: 50)
        public string Color { get; set; } // Color (length: 50)
        public string Size { get; set; } // Size (length: 50)
        public int? PcsPerCartoon { get; set; } // Pcs_per_Cartoon
        public int? TotalPcs { get; set; } // Total_Pcs
        public string Carton { get; set; } // Carton (length: 50)
        public string Remark { get; set; } // Remark (length: 50)
        public int? SNo { get; set; } // S_No
        public string ItemName { get; set; } // Item_Name (length: 50)
        public long? InsId { get; set; } // Ins_Id
        public int? NoOfCarton { get; set; } // No_of_Carton
        public long InvoiceId { get; set; } // InvoiceID
        public long Sid { get; set; } // SID
        public long? ConsigneeId { get; set; } // Consignee_Id
        public string ConsigneeAdd { get; set; } // Consignee_Add
        public string Notify { get; set; } // Notify
        public string PreCarrigeby { get; set; } // Pre_carrigeby (length: 50)
        public string PlaceOfReceipt { get; set; } // Place_of_Receipt (length: 50)
        public string VesselFlightNo { get; set; } // Vessel_Flight_No (length: 50)
        public string PortOfLoading { get; set; } // Port_of_Loading (length: 50)
        public string PortOfDischarge { get; set; } // Port_of_Discharge (length: 50)
        public string PortOfDelivery { get; set; } // Port_of_Delivery (length: 50)
        public string InvoiceNo1 { get; set; } // InvoiceNo (length: 50)
        public System.DateTime InvoiceDate { get; set; } // InvoiceDate
        public string BuyerOrderno { get; set; } // Buyer_Orderno (length: 50)
        public string OtherRefrence { get; set; } // Other_Refrence (length: 50)
        public string BuyerIfOther { get; set; } // Buyer_if_Other (length: 500)
        public string CountryOfOrigin { get; set; } // Country_of_Origin (length: 50)
        public string CountryOfDestination { get; set; } // Country_of_Destination (length: 50)
        public string Terms { get; set; } // Terms
        public string InvoiceType { get; set; } // Invoice_Type (length: 50)
        public long? InvoiceNo { get; set; } // Invoice_No
        public string ExporterRefrence { get; set; } // ExporterRefrence (length: 50)
        public string PackingRemark { get; set; } // Packing_Remark
        public System.DateTime? CustomPiDate { get; set; } // Custom_PI_Date
        public string CName { get; set; } // CName (length: 50)
        public string AddressOffice { get; set; } // Address_office
        public string AddressWork { get; set; } // Address_work
        public string Phone { get; set; } // Phone (length: 50)
        public string Fax { get; set; } // Fax (length: 50)
        public string Email { get; set; } // Email (length: 100)
        public string Web { get; set; } // Web (length: 100)
        public string Cstt { get; set; } // CSTT (length: 50)
        public string Uptt { get; set; } // UPTT (length: 50)
        public string Tin { get; set; } // TIN (length: 50)
        public string IeCode { get; set; } // IECode (length: 50)
        public string FobCif { get; set; } // FOB_CIF (length: 50)
        public string CsName { get; set; } // CSName (length: 50)
        public string ConsigneeName { get; set; } // Consignee_Name (length: 50)
        public string Caddress { get; set; } // caddress
        public string ItemInvoiceCode { get; set; } // Item_Invoice_Code (length: 50)
        public int? InvoiceSerial { get; set; } // InvoiceSerial
        public double? Amount { get; set; } // Amount
        public string AmtWords { get; set; } // Amt_Words (length: 500)
        public int? TotalQtyPcs { get; set; } // Total_Qty_Pcs
        public double? Cbm { get; set; } // CBM

        public ViewWayPackingPrint()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
