// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_FinishGoodsSupplier
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewFinishGoodsSupplier
    {
        public long Id { get; set; } // ID
        public int? ReadymadeJobworker { get; set; } // Readymade_Jobworker
        public string Code { get; set; } // Code (length: 50)
        public string Name { get; set; } // Name
        public string CPerson { get; set; } // C_Person
        public string Address { get; set; } // Address
        public string City { get; set; } // City
        public string State { get; set; } // State
        public string Pincode { get; set; } // Pincode (length: 20)
        public string Country { get; set; } // Country
        public string Zipcode { get; set; } // Zipcode (length: 20)
        public string Phoneno { get; set; } // Phoneno (length: 20)
        public string Faxno { get; set; } // Faxno (length: 20)
        public string Description { get; set; } // Description
        public string Email { get; set; } // Email
        public string Web { get; set; } // Web
        public string CsttNo { get; set; } // CSTTNo
        public string UpttNo { get; set; } // UPTTNo
        public string LtNo { get; set; } // LTNo
        public string LtName { get; set; } // LTName
        public System.DateTime? EntryDate { get; set; } // Entry_Date
        public string SessionYear { get; set; } // Session_year (length: 20)
        public int? UserId { get; set; } // UserID
        public string Mobileno { get; set; } // Mobileno (length: 20)
        public string CName { get; set; } // CName (length: 50)
        public string AddressOffice { get; set; } // Address_office

        public ViewFinishGoodsSupplier()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
