// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // The table 'View_Size' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // View_Size
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewSize
    {
        public int? Id { get; set; } // ID
        public string GroupName { get; set; } // GroupName (length: 100)
        public long? SizeId { get; set; } // Size_ID
        public double? Length { get; set; } // Length
        public double? Width { get; set; } // Width
        public double? Hight { get; set; } // Hight
        public string SizeCombination { get; set; } // Size_Combination (length: 50)

        public ViewSize()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
