// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_NonReturnableOutPass_Invoice
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewNonReturnableOutPassInvoice
    {
        public long NropInvId { get; set; } // NROP_INV_ID
        public long NropInvSNo { get; set; } // NROP_INV_SNo
        public string NropInvNo { get; set; } // NROP_INV_NO (length: 50)
        public System.DateTime NropDate { get; set; } // NROPDate
        public int SampleExport { get; set; } // Sample_Export
        public long SampleExportId { get; set; } // Sample_Export_ID
        public string SampleExportNo { get; set; } // Sample_Export_No (length: 50)
        public int Package { get; set; } // Package
        public string SessionYear { get; set; } // Session_year (length: 20)
        public int UserId { get; set; } // UserID
        public System.DateTime EntryDate { get; set; } // Entry_Date
        public long NropInvChildId { get; set; } // NROP_INV_Child_ID
        public string StyleNo { get; set; } // Style_No
        public string Qty { get; set; } // Qty (length: 10)

        public ViewNonReturnableOutPassInvoice()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
