// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_PurchaseVoucher_Tax
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewPurchaseVoucherTax
    {
        public long RmId { get; set; } // RM_ID
        public long AccountNo { get; set; } // AccountNo
        public double Amount { get; set; } // Amount
        public long PVoucherId { get; set; } // P_Voucher_Id
        public int SuppBuyerEmpId { get; set; } // Supp_Buyer_EMP_ID
        public string AccName { get; set; } // AccName (length: 100)
        public string RmName { get; set; } // RMName (length: 50)

        public ViewPurchaseVoucherTax()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
