// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_PurchaseVoucherChild
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewPurchaseVoucherChild
    {
        public string GroupName { get; set; } // Group_Name (length: 100)
        public string PName { get; set; } // P_Name
        public string AccName { get; set; } // AccName (length: 100)
        public long PVoucherId { get; set; } // P_Voucher_Id
        public string RmName { get; set; } // RMName (length: 500)
        public double Quantity { get; set; } // Quantity
        public string Unit { get; set; } // Unit (length: 50)
        public decimal Rate { get; set; } // Rate
        public long RmId { get; set; } // RM_Id
        public long? GrnId { get; set; } // GRN_Id
        public decimal? Amount { get; set; } // Amount
        public int? AccNo { get; set; } // AccNo
        public System.DateTime? PVoucherDate { get; set; } // P_Voucher_Date
        public double? TotalAmount { get; set; } // TotalAmount
        public double? TaxTotal { get; set; } // Tax_Total
        public double? Total { get; set; } // Total
        public double? Roundoff { get; set; } // Roundoff
        public double? VoucherAmt { get; set; } // Voucher_Amt
        public string AmtInWords { get; set; } // AmtInWords
        public string Remark { get; set; } // Remark
        public int? SipOrDirect { get; set; } // SIP_or_Direct
        public string Billno { get; set; } // Billno (length: 50)
        public System.DateTime? BillDate { get; set; } // BillDate
        public long? PVoucherSId { get; set; } // P_Voucher_SId
        public string Gipno { get; set; } // GIPNO (length: 20)
        public System.DateTime? GipDate { get; set; } // GIPDate

        public ViewPurchaseVoucherChild()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
