// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Order_PI
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewOrderPi
    {
        public int OrderId { get; set; } // Order_Id
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public System.DateTime Date { get; set; } // Date
        public int IssuedBy { get; set; } // Issued_By
        public string ItemCode { get; set; } // ItemCode (length: 500)
        public string Quality { get; set; } // Quality (length: 50)
        public string ItemSize { get; set; } // Item_Size (length: 50)
        public string Name { get; set; } // Name (length: 50)
        public int? FItemId { get; set; } // FItem_Id
        public int? Quantity { get; set; } // Quantity
        public string Color { get; set; } // Color (length: 50)
        public string ItemCode1 { get; set; } // ItemCode1 (length: 500)
        public string Brand { get; set; } // Brand (length: 50)
        public int Tid { get; set; } // TID
        public string TranportName { get; set; } // TranportName (length: 50)
        public string FobCif { get; set; } // FOB_CIF (length: 50)

        public ViewOrderPi()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
