// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_For_Show_PI
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewForShowPi
    {
        public string Article { get; set; } // Article (length: 50)
        public decimal? Rate { get; set; } // Rate
        public long? Qty { get; set; } // Qty
        public decimal? Amount { get; set; } // Amount
        public decimal? Per { get; set; } // Per
        public decimal? NewRate { get; set; } // New_Rate
        public decimal? NewAmount { get; set; } // New_Amount
        public long PiSno { get; set; } // PI_SNO
        public string PiNo { get; set; } // PI_NO (length: 50)
        public System.DateTime PiDate { get; set; } // PI_Date
        public int PiCurrencyId { get; set; } // PI_Currency_ID
        public long OrderId { get; set; } // Order_ID
        public long PiId { get; set; } // PI_ID

        public ViewForShowPi()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
