// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Job_Card
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewJobCard
    {
        public long TableId { get; set; } // Table_ID
        public string JbcNo { get; set; } // JBC_NO (length: 50)
        public System.DateTime? JbcDate { get; set; } // JBC_Date
        public long? ItemId { get; set; } // Item_ID
        public string Name { get; set; } // Name (length: 50)
        public string Code { get; set; } // Code (length: 50)
        public int? Qty { get; set; } // Qty
        public string Color { get; set; } // Color (length: 50)
        public string ItemSize { get; set; } // Item_Size (length: 50)
        public int? Quantity { get; set; } // Quantity
        public string Assortment { get; set; } // Assortment (length: 50)
        public string Handtags { get; set; } // Handtags (length: 50)
        public string Sticker { get; set; } // Sticker (length: 50)
        public string Carelabel { get; set; } // Carelabel (length: 50)
        public string Mainlabel { get; set; } // Mainlabel (length: 50)
        public string Wash { get; set; } // Wash (length: 50)
        public string Wax { get; set; } // Wax (length: 50)
        public string Brand { get; set; } // Brand (length: 50)
        public string String { get; set; } // String (length: 500)
        public string WashableLable { get; set; } // WashableLable (length: 500)
        public string Embossment { get; set; } // Embossment (length: 50)
        public string Lining { get; set; } // Lining (length: 50)
        public string Finish { get; set; } // Finish (length: 50)
        public string LiningColour { get; set; } // Lining_Colour (length: 50)
        public System.DateTime DeliveryDate { get; set; } // Delivery_Date
        public System.DateTime ProdStatrtingKeyDate { get; set; } // ProdStatrtingKeyDate
        public System.DateTime ProdApprovalKeyDate { get; set; } // ProdApprovalKeyDate
        public string OrderNo { get; set; } // Order_No (length: 50)
        public System.DateTime Date { get; set; } // Date
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public string OrderComments { get; set; } // Order_Comments (length: 500)
        public string JobCardComments { get; set; } // Job_Card_Comments
        public string Trimming { get; set; } // Trimming (length: 50)
        public string Stitching { get; set; } // Stitching (length: 50)
        public int Id { get; set; } // ID
        public string SupervisorName { get; set; } // SupervisorName (length: 50)
        public int Expr3 { get; set; } // Expr3
        public string SupervisorId { get; set; } // Supervisor_ID (length: 10)
        public string CareLabelNo { get; set; } // CareLabelNo (length: 50)
        public int BelongTo { get; set; } // BelongTo
        public string ItemCode { get; set; } // ItemCode (length: 50)
        public int? ShQty { get; set; } // Sh_Qty
        public string Expr1 { get; set; } // Expr1 (length: 50)
        public int? ProQty { get; set; } // Pro_Qty
        public int? Treatment { get; set; } // Treatment
        public string TreatmentName { get; set; } // Treatment_Name (length: 50)
        public int? TreatmentId { get; set; } // Treatment_ID

        public ViewJobCard()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
