// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Sample_Invoice
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewSampleInvoice
    {
        public long SiId { get; set; } // SI_ID
        public long SiSessionId { get; set; } // SI_Session_ID
        public string SiNo { get; set; } // SI_No (length: 50)
        public System.DateTime SiDate { get; set; } // SI_Date
        public string BuyerOrderno { get; set; } // Buyer_Orderno (length: 50)
        public string OtherRefrence { get; set; } // Other_Refrence (length: 50)
        public string BuyerIfOther { get; set; } // Buyer_if_Other (length: 50)
        public long? ConsigneeId { get; set; } // Consignee_Id
        public string ConsigneeAdd { get; set; } // Consignee_Add
        public string CountryOfOrigin { get; set; } // Country_of_Origin (length: 50)
        public string CountryOfDestination { get; set; } // Country_of_Destination (length: 50)
        public string Terms { get; set; } // Terms
        public string PreCarrigeby { get; set; } // Pre_carrigeby (length: 50)
        public string PlaceOfReceipt { get; set; } // Place_of_Receipt (length: 50)
        public string VesselFlightNo { get; set; } // Vessel_Flight_No (length: 50)
        public string PortOfLoading { get; set; } // Port_of_Loading (length: 50)
        public string PortOfDischarge { get; set; } // Port_of_Discharge (length: 50)
        public string FinalDestination { get; set; } // Final_Destination (length: 50)
        public decimal? InvoiceAmount { get; set; } // Invoice_Amount
        public string AmtWords { get; set; } // AmtWords
        public int CurrencyId { get; set; } // Currency_ID
        public string SessionYear { get; set; } // Session_Year (length: 20)
        public int UserId { get; set; } // UserID
        public string PodNo { get; set; } // POD_No (length: 50)
        public long? ItemId { get; set; } // Item_Id
        public string StyleNo { get; set; } // Style_No (length: 50)
        public string OrderNo { get; set; } // Order_No (length: 50)
        public int? Qty { get; set; } // Qty
        public string Chargeable { get; set; } // Chargeable (length: 5)
        public decimal? Price { get; set; } // Price
        public decimal? Amount { get; set; } // Amount
        public System.DateTime? PodDate { get; set; } // POD_Date
        public string Name { get; set; } // Name (length: 50)
        public string Quality { get; set; } // Quality (length: 50)
        public string Customer { get; set; } // Customer (length: 50)
        public string CreatedBy { get; set; } // Created_By (length: 50)
        public string Unit { get; set; } // Unit (length: 50)
        public string CName { get; set; } // CName (length: 50)
        public string AddressOffice { get; set; } // Address_office
        public string AddressWork { get; set; } // Address_work
        public string Phone { get; set; } // Phone (length: 50)
        public string Fax { get; set; } // Fax (length: 50)
        public string Cstt { get; set; } // CSTT (length: 50)
        public string Uptt { get; set; } // UPTT (length: 50)
        public string Tin { get; set; } // TIN (length: 50)
        public string PanNo { get; set; } // PANNo (length: 50)
        public int? NoOfPkg { get; set; } // NoOfPkg
        public string CsName { get; set; } // CSName (length: 50)
        public string ConsName { get; set; } // Cons_Name (length: 50)
        public string Color { get; set; } // Color (length: 50)
        public int? SampleType { get; set; } // Sample_type
        public string AccountNo { get; set; } // Account_No (length: 100)

        public ViewSampleInvoice()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
