// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Show_Packing
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewShowPacking
    {
        public long OrderId { get; set; } // Order_ID
        public string PckNo { get; set; } // PCK_No (length: 50)
        public long PckId { get; set; } // PCK_Id
        public System.DateTime PckDate { get; set; } // PCK_Date
        public long Sid { get; set; } // SID
        public int NoofOuter { get; set; } // Noof_Outer
        public int Pcs { get; set; } // Pcs
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public int PackAssNo { get; set; } // Pack_Ass_No
        public string Diemension { get; set; } // Diemension (length: 50)
        public int TotalInner { get; set; } // Total_Inner
        public double GrossWt { get; set; } // Gross_wt
        public double NetWt { get; set; } // Net_wt
        public double VolWt { get; set; } // Vol_wt
        public double Cbm { get; set; } // CBM
        public string Item { get; set; } // Item
        public int TotalOuter { get; set; } // Total_Outer
        public int Expr1 { get; set; } // Expr1
        public double TotalGross { get; set; } // Total_Gross
        public double TotalNet { get; set; } // Total_Net
        public double TotalVol { get; set; } // Total_Vol
        public double TotalCbm { get; set; } // Total_CBM
        public double? VolWt6 { get; set; } // Vol_wt_6
        public long? InsId { get; set; } // Ins_ID
        public string Assorment { get; set; } // Assorment

        public ViewShowPacking()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
