// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Packing_Inst
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewPackingInst
    {
        public int? FItemId { get; set; } // FItem_Id
        public int OrderId { get; set; } // Order_Id
        public int? Quantity { get; set; } // Quantity
        public string OrderNo { get; set; } // Order_No (length: 50)
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public System.DateTime Date { get; set; } // Date
        public string ItemCode { get; set; } // ItemCode (length: 50)
        public string Code { get; set; } // Code (length: 50)

        public ViewPackingInst()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
