// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Message_RMADD
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewMessageRmadd
    {
        public long Id { get; set; } // ID
        public long ItemId { get; set; } // Item_ID
        public int MessageFrom { get; set; } // Message_From
        public System.DateTime MessageDate { get; set; } // Message_Date
        public string MessageText { get; set; } // Message_Text
        public short MessageStatus { get; set; } // Message_Status
        public string UName { get; set; } // UName (length: 50)
        public string ItemCode { get; set; } // ItemCode (length: 50)
        public short ReadByOrder { get; set; } // Read_BY_Order
        public System.DateTime DoneDate { get; set; } // Done_Date

        public ViewMessageRmadd()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
