// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_PriceQuote
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewPriceQuote
    {
        public int? Expr1 { get; set; } // Expr1
        public int PriceQuoteId { get; set; } // PriceQuoteID
        public int? FitemId { get; set; } // Fitem_Id
        public int? BrandId { get; set; } // Brand_Id
        public System.DateTime? Date { get; set; } // Date
        public string Currency { get; set; } // Currency (length: 50)
        public decimal? ConversionRate { get; set; } // ConversionRate
        public string FobCif { get; set; } // FOB_CIF (length: 50)
        public string AirCfa { get; set; } // AIR_CFA (length: 50)
        public string PrinceRange { get; set; } // Prince_Range (length: 50)
        public decimal? QuatePrice { get; set; } // Quate_Price
        public string Remarks { get; set; } // Remarks
        public int? FinalQuats { get; set; } // FinalQuats
        public string Brand { get; set; } // Brand (length: 50)
        public string Description { get; set; } // Description (length: 100)

        public ViewPriceQuote()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
