// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_CartonDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewCartonDetail
    {
        public int CartonId { get; set; } // CartonID
        public double Length { get; set; } // Length
        public double Width { get; set; } // Width
        public double Height { get; set; } // Height
        public double Weight { get; set; } // Weight
        public string Dimension { get; set; } // Dimension (length: 50)
        public string Description { get; set; } // Description
        public int? UserId { get; set; } // UserID
        public int? OuterInner { get; set; } // Outer_Inner
        public int? BrandId { get; set; } // Brand_Id
        public string Brand { get; set; } // Brand (length: 50)

        public ViewCartonDetail()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
