// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_For_Show_MCH
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewForShowMch
    {
        public long MchId { get; set; } // MCH_ID
        public string MchNo { get; set; } // MCH_NO (length: 50)
        public System.DateTime MchDate { get; set; } // MCH_Date
        public int MchCurrencyId { get; set; } // MCH_Currency_ID
        public long OrderId { get; set; } // Order_ID
        public string Article { get; set; } // Article (length: 50)
        public decimal? Sp { get; set; } // SP
        public long? Qty { get; set; } // Qty
        public decimal? AmtInCurrency { get; set; } // Amt_In_Currency
        public decimal? Per { get; set; } // Per
        public decimal? MakingChargeInCurrency { get; set; } // Making_Charge_In_Currency
        public decimal? Conversion { get; set; } // Conversion
        public decimal? MakingChargeInr { get; set; } // Making_Charge_INR
        public decimal? MakingAmountInr { get; set; } // Making_Amount_INR
        public long? FItemId { get; set; } // FItem_Id

        public ViewForShowMch()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
