// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Cutting
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewCutting
    {
        public long TableId { get; set; } // Table_ID
        public long CuttingId { get; set; } // Cutting_ID
        public string CuttingNo { get; set; } // Cutting_NO (length: 50)
        public System.DateTime CuttingDate { get; set; } // Cutting_Date
        public string JbcNo { get; set; } // JBC_NO (length: 50)
        public long RmId { get; set; } // RM_ID
        public int NoOfPcs { get; set; } // NoOfPcs
        public int QcOnProcess { get; set; } // QC_On_Process
        public int? QcPcs { get; set; } // QC_Pcs
        public int Aproved { get; set; } // Aproved
        public string Comments { get; set; } // Comments
        public string SessionYear { get; set; } // Session_Year (length: 50)
        public int UserId { get; set; } // User_ID
        public string FullName { get; set; } // Full_Name
        public string Name { get; set; } // Name (length: 50)

        public ViewCutting()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
