// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // The table 'View_Carton_in_WayInvoice' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // View_Carton_in_WayInvoice
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewCartonInWayInvoice
    {
        public long? Id { get; set; } // ID
        public long? InsId { get; set; } // Ins_Id
        public int? NoOfCarton { get; set; } // No_of_Carton

        public ViewCartonInWayInvoice()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
