// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_MakingCharges_Print
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewMakingChargesPrint
    {
        public string JbcNo { get; set; } // JBC_NO (length: 50)
        public System.DateTime VoucherDate { get; set; } // Voucher_Date
        public long OrderId { get; set; } // Order_Id
        public double Rate { get; set; } // Rate
        public double Amount { get; set; } // Amount
        public string RecordNo { get; set; } // Record_No (length: 50)
        public long VoucherId { get; set; } // Voucher_ID
        public long WorkerId { get; set; } // Worker_ID
        public string Name { get; set; } // Name
        public string ItemCode { get; set; } // ItemCode (length: 500)
        public string AddressOffice { get; set; } // Address_office
        public string AddressWork { get; set; } // Address_work
        public string CName { get; set; } // CName (length: 50)
        public string Phone { get; set; } // Phone (length: 50)
        public string Fax { get; set; } // Fax (length: 50)
        public string Email { get; set; } // Email (length: 100)
        public string Web { get; set; } // Web (length: 100)
        public string Cstt { get; set; } // CSTT (length: 50)
        public string Uptt { get; set; } // UPTT (length: 50)
        public string Tin { get; set; } // TIN (length: 50)
        public string IeCode { get; set; } // IECode (length: 50)
        public string PanNo { get; set; } // PANNo (length: 50)
        public int JbcQty { get; set; } // JBC_Qty
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public long TodayQty { get; set; } // Today_Qty
        public string AmtInWords { get; set; } // Amt_InWords
        public string VoucherNo { get; set; } // Voucher_No (length: 50)
        public System.DateTime EntryDate { get; set; } // Entry_Date

        public ViewMakingChargesPrint()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
