// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Min_Max_Alert
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewMinMaxAlert
    {
        public long RItemId { get; set; } // RItem_Id
        public string Name { get; set; } // Name (length: 50)
        public string Code { get; set; } // Code (length: 50)
        public double? MinStock { get; set; } // Min_Stock
        public double? MaxStock { get; set; } // Max_Stock
        public string FullName { get; set; } // Full_Name
        public string CostUnit { get; set; } // CostUnit (length: 50)
        public string PUnit { get; set; } // PUnit (length: 50)
        public double? Stock { get; set; } // Stock
        public long? RmCode { get; set; } // RM_Code

        public ViewMinMaxAlert()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
