// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_INPass
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewInPass
    {
        public long InPassTableId { get; set; } // INPassTable_ID
        public string Name { get; set; } // Name (length: 50)
        public string Code { get; set; } // Code (length: 50)
        public string FullName { get; set; } // Full_Name
        public long InPassId { get; set; } // INPass_ID
        public string InPassNo { get; set; } // INPass_No (length: 50)
        public System.DateTime InPassDate { get; set; } // INPass_Date
        public string Comments { get; set; } // Comments
        public string InPassBy { get; set; } // INPass_By (length: 50)
        public string SessionYear { get; set; } // Session_Year (length: 50)
        public int UserId { get; set; } // User_Id
        public long Qty { get; set; } // Qty
        public string Purpose { get; set; } // Purpose
        public string PUnit { get; set; } // PUnit (length: 50)
        public string CostUnit { get; set; } // CostUnit (length: 50)
        public long RItemId { get; set; } // RItem_Id
        public long IssueRitemId { get; set; } // Issue_Ritem_ID
        public int Sid { get; set; } // SID
        public string PName { get; set; } // P_Name
        public string IssueNo { get; set; } // IssueNo (length: 50)

        public ViewInPass()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
