// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_RMItemWise_Supplier
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewRmItemWiseSupplier
    {
        public string RmName { get; set; } // RMName
        public long BelongTo { get; set; } // belong_To
        public string Category { get; set; } // category (length: 50)
        public string Subcategory { get; set; } // subcategory (length: 50)
        public string FullName { get; set; } // Full_Name
        public long Sid { get; set; } // SID
        public string PName { get; set; } // P_Name
        public string CName { get; set; } // CName (length: 50)
        public string Address { get; set; } // Address
        public string PCode { get; set; } // P_Code (length: 50)
        public long RItemId { get; set; } // RItem_Id
        public string AddressOffice { get; set; } // Address_office
        public int? MinDays { get; set; } // Min_Days
        public string Code { get; set; } // Code (length: 50)
        public long? RmCode { get; set; } // RM_Code
        public double? ActualPurPrice { get; set; } // ActualPurPrice
        public string ActualPUnit { get; set; } // ActualPUnit (length: 50)

        public ViewRmItemWiseSupplier()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
