// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Sample_Change_Report
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewSampleChangeReport
    {
        public long RequestId { get; set; } // Request_Id
        public System.DateTime? RequestDate { get; set; } // RequestDate
        public long? FItemId { get; set; } // FItem_Id
        public string ItemCode { get; set; } // ItemCode (length: 50)
        public string ChangeMessage { get; set; } // ChangeMessage
        public string MessageFrom { get; set; } // MessageFrom (length: 50)
        public System.DateTime? ChageUpTo { get; set; } // ChageUpTo
        public int? Status { get; set; } // Status
        public string SessionYear { get; set; } // session_year (length: 20)
        public int? SmsBulk { get; set; } // SMS_Bulk
        public System.DateTime? ChangeOn { get; set; } // Change_On
        public string MessageStatus { get; set; } // Message_status (length: 1)
        public System.DateTime? ChangeReadOn { get; set; } // Change_Read_On

        public ViewSampleChangeReport()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
