// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_OrderPending
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewOrderPending
    {
        public string CName { get; set; } // CName (length: 50)
        public string AddressOffice { get; set; } // Address_office
        public int OrderId { get; set; } // Order_Id
        public int? SmsBulk { get; set; } // SMS_BULK
        public string OrderNo { get; set; } // Order_No (length: 50)
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public System.DateTime Date { get; set; } // Date
        public System.DateTime ProdApprovalKeyDate { get; set; } // ProdApprovalKeyDate
        public System.DateTime ProdStatrtingKeyDate { get; set; } // ProdStatrtingKeyDate
        public System.DateTime ShipmentApprovlKeyDate { get; set; } // ShipmentApprovlKeyDate
        public int IssuedBy { get; set; } // Issued_By
        public System.DateTime? DeliveryDate { get; set; } // Delivery_Date
        public double? MinDelTime { get; set; } // MinDelTime
        public int? Transport { get; set; } // Transport
        public string TransportComment { get; set; } // TransportComment
        public string SessionYear { get; set; } // Session_year (length: 20)
        public int UserId { get; set; } // UserID
        public int? PurchaseRead { get; set; } // Purchase_Read
        public string Comments { get; set; } // Comments
        public int? Instruction { get; set; } // Instruction
        public int? AfterNoOfDays { get; set; } // After_No_OfDays
        public int? MaterialStatus { get; set; } // Material_Status
        public System.DateTime? EntryModifyDate { get; set; } // Entry_ModifyDate

        public ViewOrderPending()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
