// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Capacity
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewCapacity
    {
        public int? Id { get; set; } // ID
        public string Name { get; set; } // Name (length: 50)
        public int? Year { get; set; } // Year
        public string WeekName { get; set; } // Week_Name (length: 50)
        public int? WeekId { get; set; } // Week_Id
        public int? BulkCapacity { get; set; } // BULK_Capacity
        public int? SmsCapacity { get; set; } // SMS_Capacity
        public long? CategoryId { get; set; } // Category_Id
        public System.DateTime StartDate { get; set; } // Start_Date
        public System.DateTime EndDate { get; set; } // End_Date
        public int NoOfDays { get; set; } // No_Of_Days
        public int? SampleCapacity { get; set; } // Sample_Capacity
        public string Comment { get; set; } // Comment (length: 250)
        public int? BulkOrders { get; set; } // Bulk_Orders
        public int? SmsOrders { get; set; } // SMS_Orders

        public ViewCapacity()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
