// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_MenOutPass
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewMenOutPass
    {
        public long MenopId { get; set; } // MENOP_ID
        public int MenopSerialNo { get; set; } // MENOP_Serial_No
        public string MenopNo { get; set; } // MENOP_No (length: 50)
        public System.DateTime MenopDate { get; set; } // MENOP_Date
        public int StaffContractor { get; set; } // Staff_Contractor
        public string StaffName { get; set; } // Staff_Name (length: 100)
        public int NoOfPerson { get; set; } // No_of_Person
        public string Purpose { get; set; } // Purpose (length: 50)
        public string CName { get; set; } // CName (length: 50)
        public string AddressOffice { get; set; } // Address_office
        public string AddressWork { get; set; } // Address_work

        public ViewMenOutPass()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
