// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Order_in_Week
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewOrderInWeek
    {
        public string OrderNo { get; set; } // Order_No (length: 50)
        public System.DateTime Date { get; set; } // Date
        public System.DateTime? DeliveryDate { get; set; } // Delivery_Date
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public string Code { get; set; } // Code (length: 500)
        public string Brand { get; set; } // Brand (length: 50)
        public string Color { get; set; } // Color (length: 50)
        public int? Quantity { get; set; } // Quantity
        public int? SmsBulk { get; set; } // SMS_BULK
        public int? FItemId { get; set; } // FItem_Id

        public ViewOrderInWeek()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
