// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_ProductSearchPrint
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewProductSearchPrint
    {
        public long FItemId { get; set; } // FItem_Id
        public string ItemCode { get; set; } // ItemCode (length: 500)
        public long OderFItemId { get; set; } // Oder_FItem_Id
        public string OderItemCode { get; set; } // Oder_ItemCode (length: 500)
        public string OrderNo { get; set; } // Order_No (length: 50)
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public System.DateTime? Date { get; set; } // Date
        public int? SmsBulk { get; set; } // SMS_BULK
        public string IbName { get; set; } // IBName (length: 50)

        public ViewProductSearchPrint()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
