// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_RMIncosting
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewRmIncosting
    {
        public long RItemId { get; set; } // RItem_Id
        public string Code { get; set; } // Code (length: 50)
        public int? MasterBelongTo { get; set; } // MasterBelongTo
        public string FullName { get; set; } // Full_Name
        public string RmName { get; set; } // RMName
        public string Name { get; set; } // Name (length: 50)
        public int BelongTo { get; set; } // BelongTo

        public ViewRmIncosting()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
