// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_IssueRMForSample
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewIssueRmForSample
    {
        public long IssueId { get; set; } // IssueID
        public System.DateTime IrmDate { get; set; } // IRMDate
        public long SampleId { get; set; } // SampleId
        public double? IssueQty { get; set; } // IssueQty
        public string Name { get; set; } // Name
        public int IssueTo { get; set; } // IssueTo
        public string RMname { get; set; } // RMname (length: 50)
        public string Code { get; set; } // Code (length: 50)
        public long? Rmid { get; set; } // RMID
        public string CostUnit { get; set; } // CostUnit (length: 50)
        public string FullName { get; set; } // Full_Name
        public int? Rid { get; set; } // RID
        public int? Sid { get; set; } // SID
        public int? Side { get; set; } // Side
        public string RackNo { get; set; } // RackNo (length: 200)
        public string PName { get; set; } // P_Name
        public string Comments { get; set; } // Comments (length: 500)

        public ViewIssueRmForSample()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
