// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_For_MakingCharges
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewForMakingCharge
    {
        public string Expr1 { get; set; } // Expr1 (length: 50)
        public string OrderNo { get; set; } // Order_No (length: 50)
        public string ItemCode { get; set; } // ItemCode (length: 50)
        public long JbcId { get; set; } // JBC_ID
        public long JbcSNo { get; set; } // JBC_SNo
        public System.DateTime JbcDate { get; set; } // JBC_Date
        public int JbcQty { get; set; } // JBC_Qty
        public long WorkerId { get; set; } // Worker_ID
        public long PlanId { get; set; } // Plan_Id
        public long OrderId { get; set; } // Order_Id
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public long ItemId { get; set; } // Item_Id
        public int PlanQty { get; set; } // Plan_Qty
        public string JbcNo { get; set; } // JBC_No (length: 50)
        public string Name { get; set; } // Name

        public ViewForMakingCharge()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
