// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Show_Skiving
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewShowSkiving
    {
        public long? SkivingQty { get; set; } // Skiving_Qty
        public string Spec { get; set; } // Spec (length: 50)
        public long? QcQty { get; set; } // Qc_Qty
        public System.DateTime SkivingDate { get; set; } // Skiving_Date
        public long PlanId { get; set; } // Plan_Id
        public string Comments { get; set; } // Comments (length: 150)
        public long Expr1 { get; set; } // Expr1
        public long SkivingTid { get; set; } // Skiving_TID

        public ViewShowSkiving()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
