// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_SampleInMColour
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewSampleInMColour
    {
        public long FItemId { get; set; } // FItem_Id
        public int ColorId { get; set; } // Color_Id
        public int FinishId { get; set; } // Finish_Id
        public double Qty { get; set; } // Qty
        public string ClName { get; set; } // CLName (length: 50)
        public string MfName { get; set; } // MFName (length: 50)

        public ViewSampleInMColour()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
