// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_ReadymadeReceive
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewReadymadeReceive
    {
        public long PlanId { get; set; } // Plan_Id
        public long OrderId { get; set; } // Order_Id
        public System.DateTime PlanDate { get; set; } // Plan_Date
        public int PlanQty { get; set; } // Plan_Qty
        public int SupervisorId { get; set; } // Supervisor_Id
        public string Name { get; set; } // Name
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public string FName { get; set; } // FName (length: 50)
        public string Code { get; set; } // Code (length: 50)
        public int PlanFor { get; set; } // Plan_For

        public ViewReadymadeReceive()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
