// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_MultiFinish_in_Sample
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewMultiFinishInSample
    {
        public long FItemId { get; set; } // FItem_Id
        public int Mfid { get; set; } // MFID
        public string MfName { get; set; } // MFName (length: 50)

        public ViewMultiFinishInSample()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
