// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Week_Days
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewWeekDay
    {
        public int WeekDaysId { get; set; } // Week_DaysId
        public int Year { get; set; } // Year
        public int WeekId { get; set; } // Week_Id
        public int NoOfDays { get; set; } // No_Of_Days
        public string WeekName { get; set; } // Week_Name (length: 50)
        public System.DateTime StartDate { get; set; } // Start_Date
        public System.DateTime EndDate { get; set; } // End_Date
        public string Comment { get; set; } // Comment (length: 250)

        public ViewWeekDay()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
