// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Costing
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewCosting
    {
        public long CostingId { get; set; } // Costing_Id
        public int Cid { get; set; } // CID
        public string CsName { get; set; } // CSName (length: 50)
        public decimal CRate { get; set; } // CRate
        public string FobCif { get; set; } // FOB_CIF (length: 50)
        public string FreightBy { get; set; } // Freight_By (length: 50)
        public decimal CAmount { get; set; } // CAmount
        public decimal? HighCAmount { get; set; } // HighCAmount
        public decimal? MediumCAmount { get; set; } // MediumCAmount
        public decimal? LowCAmount { get; set; } // LowCAmount
        public decimal? BAmount { get; set; } // BAmount
        public decimal? HighBAmount { get; set; } // HighBAmount
        public decimal? MediumBAmount { get; set; } // MediumBAmount
        public decimal? LowBAmount { get; set; } // LowBAmount
        public int SerialNo { get; set; } // SerialNo
        public string SessionYear { get; set; } // Session_year (length: 20)
        public int? UserId { get; set; } // UserID
        public string Name { get; set; } // Name (length: 50)
        public string ShortName { get; set; } // ShortName (length: 50)
        public string SubCode { get; set; } // Sub_Code (length: 50)
        public string Code { get; set; } // Code (length: 500)
        public int ItOrCat { get; set; } // It_OR_Cat
        public string ItemCode { get; set; } // ItemCode (length: 500)
        public string Size { get; set; } // Size (length: 50)
        public string GroupName { get; set; } // Group_Name (length: 50)
        public long FItemId { get; set; } // FItem_Id
        public string Customer { get; set; } // Customer (length: 50)
        public int? FinishStatus { get; set; } // Finish_Status

        public ViewCosting()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
