// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_NROP_CP
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewNropCp
    {
        public long NropTableId { get; set; } // NROP_Table_ID
        public long NropId { get; set; } // NROP_ID
        public string NropNo { get; set; } // NROP_No (length: 50)
        public System.DateTime NropDate { get; set; } // NROP_Date
        public string Comments { get; set; } // Comments
        public string OutPassBy { get; set; } // OutPass_By (length: 50)
        public string SessionYear { get; set; } // Session_year (length: 50)
        public int UserId { get; set; } // UserID
        public long CapId { get; set; } // CapID
        public int Qty { get; set; } // Qty
        public string Purpose { get; set; } // Purpose
        public string CapCode { get; set; } // CapCode (length: 50)
        public string CapName { get; set; } // CapName (length: 50)
        public string SubCategoryName { get; set; } // SubCategory_Name (length: 50)

        public ViewNropCp()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
