// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_QCReport
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewQcReport
    {
        public int QcProcessId { get; set; } // Qc_Process_Id
        public long PlanId { get; set; } // Plan_Id
        public string ItemCode { get; set; } // ItemCode (length: 500)
        public System.DateTime QcDate { get; set; } // Qc_Date
        public string Remarks { get; set; } // Remarks
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public int PlanQty { get; set; } // Plan_Qty
        public int ItemId { get; set; } // Item_Id

        public ViewQcReport()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
