// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_ReadymadeReceiveReport
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewReadymadeReceiveReport
    {
        public long PlanId { get; set; } // Plan_Id
        public long OrderId { get; set; } // Order_Id
        public System.DateTime PlanDate { get; set; } // Plan_Date
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public string Name { get; set; } // Name (length: 50)
        public string WorkplanSupervisor { get; set; } // Workplan_Supervisor
        public long ReceiveId { get; set; } // ReceiveID
        public string ReceiveNo { get; set; } // ReceiveNo (length: 50)
        public System.DateTime ReceiveDate { get; set; } // ReceiveDate
        public double ReceiveQty { get; set; } // ReceiveQty
        public string ReceiveBy { get; set; } // ReceiveBy (length: 50)
        public string Code { get; set; } // Code (length: 500)
        public long FItemId { get; set; } // FItem_Id
        public System.DateTime Date { get; set; } // Date
        public int ReadymadeOrJobwork { get; set; } // Readymade_Or_Jobwork
        public string ItemCode { get; set; } // ItemCode (length: 500)
        public long Id { get; set; } // ID
        public long SubWpId { get; set; } // SubWP_ID
        public string SubworkplanSupervisor { get; set; } // Subworkplan_Supervisor
        public string SessionYear { get; set; } // Session_Year (length: 20)
        public int UserId { get; set; } // UserId
        public System.DateTime EntryDate { get; set; } // EntryDate
        public int SipStatus { get; set; } // SIP_Status
        public System.DateTime SipDate { get; set; } // SIP_Date
        public int SipUser { get; set; } // SIP_User
        public int? SipQty { get; set; } // SIP_Qty
        public int PlanQty { get; set; } // Plan_Qty
        public string SubWpQty { get; set; } // SubWP_Qty (length: 10)

        public ViewReadymadeReceiveReport()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
