// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_AssignRackNo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewAssignRackNo
    {
        public long Rid { get; set; } // RID
        public long RItemId { get; set; } // RItem_Id
        public int? Sid { get; set; } // SID
        public double? OpRackStock { get; set; } // Op_RackStock
        public double? Side { get; set; } // Side
        public System.DateTime? EDate { get; set; } // E_Date
        public string SessionYear { get; set; } // Session_Year (length: 20)
        public int? UserId { get; set; } // UserId
        public string Name { get; set; } // Name (length: 50)
        public string Code { get; set; } // Code (length: 50)
        public string PName { get; set; } // P_Name
        public string RackNo { get; set; } // RackNo (length: 200)
        public string PUnit { get; set; } // PUnit (length: 50)

        public ViewAssignRackNo()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
