// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Stock_On_Rack
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewStockOnRack
    {
        public string RackNo { get; set; } // RackNo (length: 200)
        public int? Store { get; set; } // Store
        public string Code { get; set; } // Code (length: 50)
        public long RItemId { get; set; } // RItem_Id
        public string FullName { get; set; } // Full_Name
        public string PName { get; set; } // P_Name
        public double? OpRackStock { get; set; } // Op_RackStock
        public double? Side { get; set; } // Side
        public long Rid { get; set; } // RID
        public string Name { get; set; } // Name (length: 50)
        public long Sid { get; set; } // SID

        public ViewStockOnRack()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
