// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_NonReturnableOutpass_RM
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewNonReturnableOutpassRm
    {
        public int OutPassRmId { get; set; } // OutPassRM_Id
        public int? OutPassSNo { get; set; } // OutPass_SNo
        public System.DateTime? OutPassDate { get; set; } // OutPassDate
        public string OutPassNo { get; set; } // OutPassNo (length: 50)
        public string SessionYear { get; set; } // Session_year (length: 50)
        public int IssueQty { get; set; } // IssueQty
        public int Rmid { get; set; } // RMID
        public string RackNo { get; set; } // RackNo (length: 200)
        public int Rid { get; set; } // RID
        public int Sid { get; set; } // SID
        public string PName { get; set; } // P_Name
        public int Side { get; set; } // Side
        public string Comments { get; set; } // Comments (length: 150)
        public string Category { get; set; } // Category (length: 50)
        public string Subacategory { get; set; } // Subacategory (length: 50)
        public string Name { get; set; } // Name (length: 50)
        public string Code { get; set; } // Code (length: 50)
        public string FullName { get; set; } // Full_Name
        public string PUnit { get; set; } // PUnit (length: 50)
        public string CostUnit { get; set; } // CostUnit (length: 50)

        public ViewNonReturnableOutpassRm()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
