// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_RMInMultipleOrders
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewRmInMultipleOrder
    {
        public string OrderNo { get; set; } // Order_No (length: 50)
        public int OrderId { get; set; } // Order_Id
        public int? FItemId { get; set; } // FItem_Id
        public string FItemName { get; set; } // FItem_Name (length: 50)
        public string Item { get; set; } // Item (length: 100)
        public long? ItemId { get; set; } // Item_Id
        public string Name { get; set; } // Name (length: 50)
        public string Rm { get; set; } // RM
        public int? ProQty { get; set; } // Pro_Qty
        public int? ShQty { get; set; } // Sh_Qty
        public int? Quantity { get; set; } // Quantity
        public int? FinalQty { get; set; } // Final_Qty
        public double? Reqd { get; set; } // REQD
        public string Code { get; set; } // Code (length: 50)
        public double? MaxWastage { get; set; } // Max_Wastage
        public double? BomWas { get; set; } // BOMWas
        public double? ActualRequired { get; set; } // Actual_Required
        public double? ActualRequiredAfterWas { get; set; } // Actual_Required_After_Was
        public long SubcategoryId { get; set; } // Subcategory_id
        public string SubcategoryName { get; set; } // Subcategory_Name (length: 50)
        public long CategoryId { get; set; } // Category_id
        public string CategoryName { get; set; } // Category_Name (length: 50)

        public ViewRmInMultipleOrder()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
