// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Item_Costing_RM
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewItemCostingRm
    {
        public long FItemId { get; set; } // FItem_Id
        public string ItemCode { get; set; } // ItemCode (length: 500)
        public long CostingId { get; set; } // Costing_Id
        public string Item { get; set; } // Item (length: 100)
        public long? RmId { get; set; } // RM_ID
        public double? Reqd { get; set; } // REQD
        public string Pcs { get; set; } // PCS (length: 50)
        public double? ActualQty { get; set; } // Actual_Qty
        public double? BomWas { get; set; } // BOMWas

        public ViewItemCostingRm()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
