// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Bill_Report
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewBillReport
    {
        public long BillId { get; set; } // Bill_ID
        public long Grnid { get; set; } // GRNID
        public string Pono { get; set; } // PONO (length: 20)
        public long VoucherNo { get; set; } // VoucherNo
        public System.DateTime VoucherDate { get; set; } // VoucherDate
        public string Gipno { get; set; } // GIPNO (length: 20)
        public long SupplierId { get; set; } // Supplier_Id
        public string PName { get; set; } // P_Name
        public string BillNoFromGrn { get; set; } // BillNo_from_GRN (length: 50)
        public System.DateTime GipDate { get; set; } // GIPDate
        public decimal AmtAfterTax { get; set; } // Amt_After_tax

        public ViewBillReport()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
