// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Sample_RM_Print
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewSampleRmPrint
    {
        public long FItemId { get; set; } // FItem_ID
        public string Category { get; set; } // Category (length: 50)
        public string SubCategory { get; set; } // SubCategory (length: 50)
        public string Item { get; set; } // Item (length: 100)
        public long? RItemId { get; set; } // RItem_ID
        public string Code { get; set; } // Code (length: 50)

        public ViewSampleRmPrint()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
