// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Stock_Reserve
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewStockReserve
    {
        public string ReserveNo { get; set; } // Reserve_No (length: 50)
        public long? ReserveStock { get; set; } // Reserve_Stock
        public System.DateTime? ReserveDate { get; set; } // Reserve_Date
        public long? ReserveItemId { get; set; } // Reserve_ItemID
        public string SessionYear { get; set; } // Session_year (length: 20)
        public int? UserId { get; set; } // UserID
        public long? ReserveId { get; set; } // Reserve_ID
        public string FullName { get; set; } // Full_Name
        public string Name { get; set; } // Name (length: 50)
        public string ShortName { get; set; } // ShortName (length: 50)
        public string Code { get; set; } // Code (length: 500)
        public string ItemCode { get; set; } // ItemCode (length: 500)
        public long? ReserveForItemId { get; set; } // Reserve_For_ItemID
        public string PUnit { get; set; } // PUnit (length: 50)
        public long? ReserveForOrderId { get; set; } // Reserve_For_Order_Id
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public string Expr1 { get; set; } // Expr1 (length: 50)
        public string Rm { get; set; } // RM
        public string CName { get; set; } // CName (length: 50)
        public string AddressOffice { get; set; } // Address_office
        public string FtCode { get; set; } // FT_Code (length: 50)

        public ViewStockReserve()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
