// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_ClosingReport
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewClosingReport
    {
        public long ClosingTid { get; set; } // Closing_TID
        public System.DateTime ClosingDate { get; set; } // Closing_Date
        public long? ClosingQty { get; set; } // Closing_Qty
        public long? QcQty { get; set; } // Qc_Qty
        public long? RejectQty { get; set; } // Reject_Qty
        public string Comments { get; set; } // Comments (length: 150)
        public long PlanId { get; set; } // Plan_id

        public ViewClosingReport()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
