// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_For_MaterialReport
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewForMaterialReport
    {
        public long FItemId { get; set; } // FItem_Id
        public string Name { get; set; } // Name (length: 50)
        public string ItemCode { get; set; } // ItemCode (length: 50)
        public System.DateTime? CreatedDate { get; set; } // Created_Date
        public System.DateTime? CreationDate { get; set; } // Creation_Date

        public ViewForMaterialReport()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
