// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_JobWorkOutPass
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewJobWorkOutPass
    {
        public double Quantity { get; set; } // Quantity
        public int RmId { get; set; } // RM_ID
        public long IssueId { get; set; } // Issue_ID
        public long IssueSNo { get; set; } // Issue_SNo
        public string IssueNo { get; set; } // Issue_No (length: 50)
        public System.DateTime? IssueDate { get; set; } // Issue_Date
        public string ReceiveBy { get; set; } // Receive_By (length: 50)
        public System.DateTime PlanDate { get; set; } // Plan_Date
        public int PlanFor { get; set; } // Plan_For
        public string Name { get; set; } // Name (length: 50)
        public string Code { get; set; } // Code (length: 50)
        public string Unit { get; set; } // Unit (length: 50)
        public double ReqQty { get; set; } // Req_Qty
        public long PlanId { get; set; } // Plan_Id

        public ViewJobWorkOutPass()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
