// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_printjobcard
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewPrintjobcard
    {
        public string SoNo { get; set; } // SO_No (length: 50)
        public long JobCardId { get; set; } // JobCard_Id
        public long JobCardNo { get; set; } // JobCard_No
        public long SoId { get; set; } // SO_Id
        public int ContrId { get; set; } // Contr_ID
        public System.DateTime ReqDate { get; set; } // Req_Date
        public System.DateTime DeliDate { get; set; } // Deli_Date
        public decimal JobPrice { get; set; } // Job_Price
        public string CheckedBy { get; set; } // CheckedBy (length: 50)
        public string SessionYear { get; set; } // Session_year (length: 20)
        public int? UserId { get; set; } // UserID
        public string PrdCode { get; set; } // Prd_Code (length: 50)
        public string PrdName { get; set; } // Prd_Name (length: 50)
        public string PrdColor { get; set; } // Prd_Color (length: 50)
        public int PrdPieces { get; set; } // Prd_Pieces
        public int? PrdId { get; set; } // Prd_Id
        public string ContrName { get; set; } // Contr_name (length: 50)
        public string ContrCode { get; set; } // Contr_code (length: 50)

        public ViewPrintjobcard()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
