// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_FinishItem_For_QC
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewFinishItemForQc
    {
        public long PlanId { get; set; } // Plan_Id
        public long OrderId { get; set; } // Order_Id
        public System.DateTime PlanDate { get; set; } // Plan_Date
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public string Name { get; set; } // Name (length: 50)
        public string WorkplanSupervisor { get; set; } // Workplan_Supervisor
        public string Code { get; set; } // Code (length: 500)
        public long FItemId { get; set; } // FItem_Id
        public System.DateTime Date { get; set; } // Date
        public string ItemCode { get; set; } // ItemCode (length: 500)
        public long Id { get; set; } // ID
        public string SubworkplanSupervisor { get; set; } // Subworkplan_Supervisor
        public long? SubWpId { get; set; } // SubWP_ID

        public ViewFinishItemForQc()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
