// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_Way_Invoice_Print
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewWayInvoicePrint
    {
        public long WayId { get; set; } // Way_ID
        public System.DateTime? WayDate { get; set; } // Way_Date
        public int? TotalCarton { get; set; } // Total_Carton
        public decimal? GrossWt { get; set; } // Gross_wt
        public decimal? NetWt { get; set; } // Net_wt
        public int? WayNoAgainstPacking { get; set; } // Way_No_Against_Packing
        public string SessionYear { get; set; } // Session_Year (length: 50)
        public int? UserId { get; set; } // User_Id
        public double? WayTotalAmount { get; set; } // Way_Total_Amount
        public string AmtWords { get; set; } // Amt_Words (length: 500)
        public string ItemCode { get; set; } // ItemCode (length: 50)
        public string Description { get; set; } // Description
        public string Quality { get; set; } // Quality (length: 50)
        public string Colour { get; set; } // Colour (length: 50)
        public string Size { get; set; } // Size (length: 50)
        public long Qty { get; set; } // Qty
        public double Rate { get; set; } // Rate
        public double ItemAmount { get; set; } // Item_Amount
        public string OrderNo { get; set; } // OrderNo (length: 50)
        public long SNo { get; set; } // SNo
        public string ItcHs { get; set; } // ITC_HS (length: 50)
        public long InvoiceId { get; set; } // InvoiceID
        public long Sid { get; set; } // SID
        public string ConsigneeAdd { get; set; } // Consignee_Add
        public string Notify { get; set; } // Notify
        public string PreCarrigeby { get; set; } // Pre_carrigeby (length: 50)
        public string PlaceOfReceipt { get; set; } // Place_of_Receipt (length: 50)
        public string VesselFlightNo { get; set; } // Vessel_Flight_No (length: 50)
        public string PortOfLoading { get; set; } // Port_of_Loading (length: 50)
        public string PortOfDischarge { get; set; } // Port_of_Discharge (length: 50)
        public string PortOfDelivery { get; set; } // Port_of_Delivery (length: 50)
        public string InvoiceNo1 { get; set; } // InvoiceNo (length: 50)
        public System.DateTime InvoiceDate { get; set; } // InvoiceDate
        public string BuyerOrderno { get; set; } // Buyer_Orderno (length: 50)
        public string OtherRefrence { get; set; } // Other_Refrence (length: 50)
        public string BuyerIfOther { get; set; } // Buyer_if_Other (length: 500)
        public string CountryOfOrigin { get; set; } // Country_of_Origin (length: 50)
        public string CountryOfDestination { get; set; } // Country_of_Destination (length: 50)
        public string Terms { get; set; } // Terms
        public long? Cid { get; set; } // CID
        public string InvoiceType { get; set; } // Invoice_Type (length: 50)
        public long? InvoiceNo { get; set; } // Invoice_No
        public string ExporterRefrence { get; set; } // ExporterRefrence (length: 50)
        public string PayemntTerm { get; set; } // Payemnt_Term
        public int Id { get; set; } // ID
        public string CName { get; set; } // CName (length: 50)
        public string AddressOffice { get; set; } // Address_office
        public string AddressWork { get; set; } // Address_work
        public string Phone { get; set; } // Phone (length: 50)
        public string Fax { get; set; } // Fax (length: 50)
        public string Email { get; set; } // Email (length: 100)
        public string Web { get; set; } // Web (length: 100)
        public string Cstt { get; set; } // CSTT (length: 50)
        public string Uptt { get; set; } // UPTT (length: 50)
        public string Tin { get; set; } // TIN (length: 50)
        public string FobCif { get; set; } // FOB_CIF (length: 50)
        public string CsName { get; set; } // CSName (length: 50)
        public string ConsigneeName { get; set; } // Consignee_Name (length: 50)
        public string Caddress { get; set; } // caddress
        public int? InvoiceSerial { get; set; } // InvoiceSerial

        public ViewWayInvoicePrint()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
