// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_PritStorIssue
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewPritStorIssue
    {
        public long ClosingId { get; set; } // Closing_Id
        public long SIssueNo { get; set; } // SIssue_No
        public long SoId { get; set; } // SO_Id
        public long JobCardId { get; set; } // JobCard_Id
        public System.DateTime ClosingDate { get; set; } // Closing_Date
        public decimal RateClicking { get; set; } // Rate_Clicking
        public decimal RateSkiving { get; set; } // Rate_Skiving
        public string ClosingDescr { get; set; } // Closing_Descr (length: 250)
        public string SessionYear { get; set; } // Session_year (length: 20)
        public int? UserId { get; set; } // UserID
        public string RItemName { get; set; } // RItem_Name (length: 50)
        public string RItemCode { get; set; } // RItem_Code (length: 50)
        public string RItemUnit { get; set; } // RItem_Unit (length: 50)
        public double RItemQty { get; set; } // RItem_Qty
        public long RItemId { get; set; } // RItem_Id
        public long JobCardNo { get; set; } // JobCard_No
        public int ContrId { get; set; } // Contr_ID
        public System.DateTime ReqDate { get; set; } // Req_Date
        public string ContrName { get; set; } // Contr_name (length: 50)
        public string ContrCode { get; set; } // Contr_code (length: 50)

        public ViewPritStorIssue()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
