// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ERP.Domain.Entities
{

    // View_For_MCH
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class ViewForMch
    {
        public string CustOrderNo { get; set; } // Cust_Order_No (length: 50)
        public System.DateTime Date { get; set; } // Date
        public int OrderId { get; set; } // Order_Id
        public string ItemCode { get; set; } // ItemCode (length: 500)
        public int BelongTo { get; set; } // BelongTo
        public int? FItemId { get; set; } // FItem_Id
        public string OrderItemCode { get; set; } // Order_ItemCode (length: 500)
        public string Brand { get; set; } // Brand (length: 50)
        public int? Quantity { get; set; } // Quantity
        public int? ShQty { get; set; } // Sh_Qty
        public int? ProQty { get; set; } // Pro_Qty

        public ViewForMch()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
